export const searchPlaceholder = [
  'Search for your next adventure...',
  'Enter a book title, author, or genre...',
  'Find a story that inspires you...',
  'Looking for a bestseller? Try searching here...',
  'Discover new worlds, start typing...',
  'What book are you thinking of today?',
  'Search for classic literature or modern gems...',
  'Find books that match your mood...',
  'Type the name of your favorite author...',
  'Explore timeless stories, start searching...',
  'Enter a keyword to find great books...',
  'Need a recommendation? Search now...',
  'What’s the last book you loved?',
  'Looking for a fantasy epic? Search here...',
  'Enter a mystery, romance, or sci-fi title...',
  'Find your next favorite book...',
  'Search for award-winning novels...',
  'What’s on your reading list?',
  'Type a title and discover related books...',
  'Enter a book series or standalone title...',
  'Looking for non-fiction or biographies?',
  'Explore the literary world, start typing...',
  'Find the book everyone is talking about...',
  'Discover hidden literary treasures...',
  'Looking for something thought-provoking?',
  'Type a book quote to find related titles...',
  'Search for historical fiction or memoirs...',
  'What’s your next must-read?',
  'Enter a book title and start exploring...',
  'Find new releases and trending books...',
  'Searching for a classic? Type the title...',
  'Find books that changed the world...',
  'Looking for a cozy read? Start searching...',
  'Enter a book theme: adventure, mystery, love...',
  'Explore books from around the world...',
  'Find books by your favorite author...',
  'What book should you read next?',
  'Search for a novel that sparks imagination...',
  'Enter a genre to explore new stories...',
  'Discover books that match your interests...',
  'Find a book to match your mood...',
  'Looking for a book recommendation?',
  'Search for literature that leaves an impact...',
  'What book is calling your name?',
  'Find books with unforgettable characters...',
  'Type a book title to see related reads...',
  'Looking for a heartwarming story?',
  'Enter a book title or topic you love...',
  'Find stories filled with magic and wonder...',
  'Search for a book that takes you places...',
];
